export const columns = [
   {name: 'NAME', uid: 'nome'},
   {name: 'STATUS', uid: 'status'},
   {name: 'ACTIONS', uid: 'actions'},
];
export const users = [
   {
      id: 1,
      nome: 'Ana Clara da Silva',
      studentCode: '2021-0001',
      status: 'Matriculado',
      email: 'ana.silva@example.com',
   },
   {
      id: 2,
      nome: 'José Luiz dos Santos',
      studentCode: '2021-0002',
      status: 'Matriculado',
      email: 'jose.santos@example.com',
   },
   {
      id: 3,
      nome: 'Carolina Oliveira Santos',
      studentCode: '2021-0003',
      status: 'Matriculado',
      email: 'carolina.oliveira@example.com',
   },
   {
      id: 4,
      nome: 'Felipe Costa Lima',
      studentCode: '2021-0004',
      status: 'Matriculado',
      email: 'felipe.lima@example.com',
   },
   {
      id: 5,
      nome: 'Amanda Pereira Souza',
      studentCode: '2021-0005',
      status: 'Matriculado',
      email: 'amanda.souza@example.com',
   },
   {
      id: 6,
      nome: 'Lucas Santos Pereira',
      studentCode: '2021-0006',
      status: 'Matriculado',
      email: 'lucas.pereira@example.com',
   },
   {
      id: 7,
      nome: 'Mariana Almeida Lima',
      studentCode: '2021-0007',
      status: 'Matriculado',
      email: 'mariana.almeida@example.com',
   },
   {
      id: 8,
      nome: 'Pedro Henrique da Costa',
      studentCode: '2021-0008',
      status: 'Matriculado',
      email: 'pedro.costa@example.com',
   },
   {
      id: 9,
      nome: 'Juliana Oliveira Sousa',
      studentCode: '2021-0009',
      status: 'Matriculado',
      email: 'juliana.sousa@example.com',
   },
   {
      id: 10,
      nome: 'Gustavo Silva Santos',
      studentCode: '2021-0010',
      status: 'Matriculado',
      email: 'gustavo.silva@example.com',
   },
   {
      id: 11,
      nome: 'Fernanda Rodrigues Costa',
      studentCode: '2021-0011',
      status: 'Lista de espera',
      email: 'fernanda.costa@example.com',
   },
   {
      id: 12,
      nome: 'Rafaela Oliveira Lima',
      studentCode: '2021-0012',
      status: 'Lista de espera',
      email: 'rafaela.oliveira@example.com',
   },
   {
      id: 13,
      nome: 'Bruno Santos Silva',
      studentCode: '2021-0013',
      status: 'Lista de espera',
      email: 'bruno.santos@example.com',
   },
   {
      id: 14,
      nome: 'Luiza Costa Pereira',
      studentCode: '2021-0014',
      status: 'Lista de espera',
      email: 'luiza.pereira@example.com',
   },
   {
      id: 15,
      nome: 'Daniel Oliveira Rodrigues',
      studentCode: '2021-0015',
      status: 'Lista de espera',
      email: 'daniel.rodrigues@example.com',
   },
   {
      id: 16,
      nome: 'Camila Silva Almeida',
      studentCode: '2021-0016',
      status: 'Lista de espera',
      email: 'camila.almeida@example.com',
   },
   {
      id: 17,
      nome: 'Marcos Oliveira Santos',
      studentCode: '2021-0017',
      status: 'Lista de espera',
      email: 'marcos.santos@example.com',
   },
   {
      id: 18,
      nome: 'Laura Pereira Lima',
      studentCode: '2021-0018',
      status: 'Lista de espera',
      email: 'laura.pereira@example.com',
   },
   {
      id: 19,
      nome: 'Gabriel Santos Costa',
      studentCode: '2021-0019',
      status: 'Lista de espera',
      email: 'gabriel.santos@example.com',
   },
   {
      id: 20,
      nome: 'Isabela Lima Oliveira',
      studentCode: '2021-0020',
      status: 'Lista de espera',
      email: 'isabela.oliveira@example.com',
   },
];

