export const columns = [
  { name: "NAME", uid: "nome" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];
export const users = [
  {
    id: 1,
    nome: "Ana Clara da Silva",
    studentCode: "2021-0001",
    status: "Regular",
    email: "ana.silva@example.com",
  },
  {
    id: 2,
    nome: "José Luiz dos Santos",
    studentCode: "2021-0002",
    status: "Regular",
    email: "jose.santos@example.com",
  },
  {
    id: 3,
    nome: "Carolina Oliveira Santos",
    studentCode: "2021-0003",
    status: "Regular",
    email: "carolina.oliveira@example.com",
  },
  {
    id: 4,
    nome: "Felipe Costa Lima",
    studentCode: "2021-0004",
    status: "Regular",
    email: "felipe.lima@example.com",
  },
  {
    id: 5,
    nome: "Amanda Pereira Souza",
    studentCode: "2021-0005",
    status: "Regular",
    email: "amanda.souza@example.com",
  },
  {
    id: 6,
    nome: "Lucas Santos Pereira",
    studentCode: "2021-0006",
    status: "Regular",
    email: "lucas.pereira@example.com",
  },
  {
    id: 7,
    nome: "Mariana Almeida Lima",
    studentCode: "2021-0007",
    status: "Regular",
    email: "mariana.almeida@example.com",
  },
  {
    id: 8,
    nome: "Pedro Henrique da Costa",
    studentCode: "2021-0008",
    status: "Regular",
    email: "pedro.costa@example.com",
  },
  {
    id: 9,
    nome: "Juliana Oliveira Sousa",
    studentCode: "2021-0009",
    status: "Regular",
    email: "juliana.sousa@example.com",
  },
  {
    id: 10,
    nome: "Gustavo Silva Santos",
    studentCode: "2021-0010",
    status: "Regular",
    email: "gustavo.silva@example.com",
  },
  {
    id: 11,
    nome: "Fernanda Rodrigues Costa",
    studentCode: "2021-0011",
    status: "Em alerta",
    email: "fernanda.costa@example.com",
  },
  {
    id: 12,
    nome: "Rafaela Oliveira Lima",
    studentCode: "2021-0012",
    status: "Em alerta",
    email: "rafaela.oliveira@example.com",
  },
  {
    id: 13,
    nome: "Bruno Santos Silva",
    studentCode: "2021-0013",
    status: "Em alerta",
    email: "bruno.santos@example.com",
  },
  {
    id: 14,
    nome: "Luiza Costa Pereira",
    studentCode: "2021-0014",
    status: "Em alerta",
    email: "luiza.pereira@example.com",
  },
  {
    id: 15,
    nome: "Daniel Oliveira Rodrigues",
    studentCode: "2021-0015",
    status: "Em alerta",
    email: "daniel.rodrigues@example.com",
  },
  {
    id: 16,
    nome: "Camila Silva Almeida",
    studentCode: "2021-0016",
    status: "Em alerta",
    email: "camila.almeida@example.com",
  },
  {
    id: 17,
    nome: "Marcos Oliveira Santos",
    studentCode: "2021-0017",
    status: "Em alerta",
    email: "marcos.santos@example.com",
  },
  {
    id: 18,
    nome: "Laura Pereira Lima",
    studentCode: "2021-0018",
    status: "Em alerta",
    email: "laura.pereira@example.com",
  },
  {
    id: 19,
    nome: "Gabriel Santos Costa",
    studentCode: "2021-0019",
    status: "Em alerta",
    email: "gabriel.santos@example.com",
  },
  {
    id: 20,
    nome: "Isabela Lima Oliveira",
    studentCode: "2021-0020",
    status: "Em alerta",
    email: "isabela.oliveira@example.com",
  },
  {
    id: 21,
    nome: "Luiz da Silva Santos",
    studentCode: "2021-0021",
    status: "Em alerta",
    email: "luiz.santos@example.com",
  },
  {
    id: 22,
    nome: "Mariana Oliveira Costa",
    studentCode: "2021-0022",
    status: "Em alerta",
    email: "mariana.costa@example.com",
  },
  {
    id: 23,
    nome: "Rafaela Pereira Lima",
    studentCode: "2021-0023",
    status: "Em alerta",
    email: "rafaela.lima@example.com",
  },
  {
    id: 24,
    nome: "João Santos Souza",
    studentCode: "2021-0024",
    status: "Em alerta",
    email: "joao.souza@example.com",
  },
  {
    id: 25,
    nome: "Camila Costa Silva",
    studentCode: "2021-0025",
    status: "Em alerta",
    email: "camila.silva@example.com",
  },
  {
    id: 26,
    nome: "Lucas Oliveira Pereira",
    studentCode: "2021-0026",
    status: "Em alerta",
    email: "lucas.pereira@example.com",
  },
  {
    id: 27,
    nome: "Amanda Lima Santos",
    studentCode: "2021-0027",
    status: "Em alerta",
    email: "amanda.santos@example.com",
  },
  {
    id: 28,
    nome: "Gabriel Costa Oliveira",
    studentCode: "2021-0028",
    status: "Em alerta",
    email: "gabriel.oliveira@example.com",
  },
  {
    id: 29,
    nome: "Juliana Santos Pereira",
    studentCode: "2021-0029",
    status: "Em alerta",
    email: "juliana.pereira@example.com",
  },
  {
    id: 30,
    nome: "Bruno Oliveira Silva",
    studentCode: "2021-0030",
    status: "Em alerta",
    email: "bruno.silva@example.com",
  },
];
